#for dev
FROM node:21-alpine

WORKDIR /app

# Install npm dependencies
COPY package*.json ./

RUN npm install
COPY . .
RUN npm run build

CMD [ "npm", "run", "dev" ]
# CMD ["npm", "start"]
#for prod
#FROM node:16-alpine AS build
#WORKDIR /app

#COPY . .
#RUN npm install
#RUN npm run build
# Serve Application using Nginx Server
#FROM nginx:alpine
#COPY --from=build /app/dist/project-name/ /usr/share/nginx/html
#EXPOSE 80
# CMD [ "npm", "run", "preview" ]