#Stage 1
FROM node:21-alpine as build

WORKDIR /app

# Install npm dependencies
COPY package*.json ./
# install based on exact versions
RUN npm ci 
# RUN npm install
COPY . .
RUN npm run build

# CMD [ "npm", "run", "dev" ]

## Stage 2
FROM nginx:alpine
ADD ./config/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /var/www/app/
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]