services:

  client:
    container_name: client
    image: client:1.0.0
    build:
      context: ./client
    ports:
      - "3050:80"
    volumes:
      - ${API_URI}/front.env.js:/var/www/app/config/front.env.js:ro
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - tkr_network
    depends_on:
      - server

  server:
    container_name: server
    image: server:1.0.0
    build:
      context: .
    ports:
      - "8443:8443"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SSL_PASSWORD=${SSL_PASS}
    networks:
      - tkr_network
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - backups:/backups
    networks:
      - tkr_network

  backup:
    container_name: backup
    image: postgres:alpine
    volumes:
      - ./backup.sh:/backup.sh:ro
      - db-data:/var/lib/postgresql/data:ro
      - backups:/backups
    environment:
      - PGHOST=${PGHOST}
      - PGUSER=${DATABASE_USERNAME}
      - PGPASSWORD=${DATABASE_PASSWORD}
      - PGDATABASE=${POSTGRES_DB}
    depends_on:
      - database
    command: sh -c "cp /backup.sh /tmp/backup.sh && dos2unix /tmp/backup.sh && chmod +x /tmp/backup.sh && /tmp/backup.sh"
    networks:
      - tkr_network

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"   
      - "81:81"   
      - "443:443" 
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - tkr_network
networks:
  tkr_network:
    driver: bridge

volumes:
  db-data:
  backups:
  npm_data:
  npm_letsencrypt:
