version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dummyuser
      POSTGRES_PASSWORD: dummypassword
      POSTGRES_DB: andnatkrdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: